
imagev1: nerdtsai/flask-sample-app-v1
imagev2: nerdtsai/flask-sample-app-v2
replicaCount: 1

service:
  portName: http-flask
  type: LoadBalancer
  internalPort: 5000
  externalPort: 5000

ingress:
  enabled: True
  annotations:
    http.port: "5000"
  hosts: 
    - testhost
